scheme: Gemini

## 菜单设置
menu:
  home: / || home                          
  archives: /archives/ || archive          
  categories: /categories/ || th           
  tags: /tags/ || tags                     
  about: /about/ || user

## 文章更新时间去除
post_meta:
  updated_at:
    enable: false

## 搜索是否可用
local_search:
  enable: true


## 统计站点，文章的访问次数
busuanzi_count:
  enable: true

## 代码高亮
codeblock:
  # Code Highlight theme
  # All available themes: https://theme-next.js.org/highlight/
  theme:
    light: tomorrow-night
    dark: tomorrow-night

## 友情链接
links_settings:
  title: 友情链接
links:
  XZG: https://www.xzgedu.com/

footer:
  since: 2019 - 2029
